# Generated by Django 3.2.4 on 2021-06-06 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='卡牌名')),
                ('summary', models.TextField(verbose_name='卡牌描述')),
                ('type', models.CharField(default='Unit', max_length=16, verbose_name='卡牌类型')),
                ('behavior', models.TextField(verbose_name='单位行为')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('delete_flag', models.SmallIntegerField(verbose_name='删除标记')),
            ],
            options={
                'verbose_name': '卡牌',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='角色名')),
                ('summary', models.TextField(verbose_name='角色描述')),
                ('health', models.IntegerField(verbose_name='血量')),
                ('sync', models.IntegerField(verbose_name='同步值')),
                ('behavior', models.TextField(verbose_name='单位行为')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('delete_flag', models.SmallIntegerField(verbose_name='删除标记')),
            ],
            options={
                'verbose_name': '角色',
            },
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='单位名')),
                ('summary', models.TextField(verbose_name='单位描述')),
                ('health', models.IntegerField(verbose_name='血量')),
                ('sync', models.IntegerField(verbose_name='同步值')),
                ('behavior', models.TextField(verbose_name='单位行为')),
                ('unit_flag', models.IntegerField(default=0, verbose_name='单位标记')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('delete_flag', models.SmallIntegerField(verbose_name='删除标记')),
            ],
            options={
                'verbose_name': '怪物单位',
            },
        ),
        migrations.CreateModel(
            name='BattleField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='战斗名')),
                ('summary', models.TextField(verbose_name='战斗描述')),
                ('combat_log', models.TextField(verbose_name='战斗日志')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('delete_flag', models.SmallIntegerField(verbose_name='删除标记')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='账号ID')),
            ],
            options={
                'verbose_name': '战斗',
            },
        ),
    ]
