# Generated by Django 3.2.4 on 2021-06-18 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='卡牌名')),
                ('summary', models.TextField(verbose_name='卡牌描述')),
                ('type', models.CharField(choices=[('Spells', '法术牌'), ('Unit', '单位牌')], default='法术牌', max_length=16, verbose_name='卡牌类型')),
                ('power', models.IntegerField(default=1, verbose_name='费用')),
                ('material', models.CharField(default='undefined', max_length=25, verbose_name='施法材料')),
                ('waiver', models.TextField(default='undefined', verbose_name='豁免判定')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/card/%Y/%m/%d/', verbose_name='封面')),
                ('behavior', models.TextField(verbose_name='单位行为')),
                ('behavior_script', models.TextField(blank=True, null=True, verbose_name='单位行为代码')),
                ('editor', models.CharField(blank=True, max_length=25, null=True, verbose_name='编辑人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('delete_flag', models.SmallIntegerField(default=0, verbose_name='删除标记')),
            ],
            options={
                'verbose_name': '卡牌',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='角色名')),
                ('summary', models.TextField(verbose_name='角色描述')),
                ('health', models.IntegerField(verbose_name='血量')),
                ('sync', models.IntegerField(verbose_name='同步值')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/character/%Y/%m/%d/', verbose_name='封面')),
                ('behavior', models.TextField(verbose_name='单位行为')),
                ('behavior_script', models.TextField(blank=True, null=True, verbose_name='单位行为代码')),
                ('editor', models.CharField(blank=True, max_length=25, null=True, verbose_name='编辑人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('delete_flag', models.SmallIntegerField(default=0, verbose_name='删除标记')),
            ],
            options={
                'verbose_name': '角色',
            },
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='单位名')),
                ('summary', models.TextField(verbose_name='单位描述')),
                ('health', models.IntegerField(verbose_name='血量')),
                ('sync', models.IntegerField(verbose_name='同步值')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/monster/%Y/%m/%d/', verbose_name='封面')),
                ('behavior', models.TextField(verbose_name='单位行为')),
                ('behavior_script', models.TextField(blank=True, null=True, verbose_name='单位行为代码')),
                ('unit_flag', models.IntegerField(default=0, verbose_name='单位标记')),
                ('editor', models.CharField(blank=True, max_length=25, null=True, verbose_name='编辑人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('delete_flag', models.SmallIntegerField(default=0, verbose_name='删除标记')),
            ],
            options={
                'verbose_name': '怪物单位',
            },
        ),
        migrations.CreateModel(
            name='BattleField',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='战斗名')),
                ('summary', models.TextField(blank=True, verbose_name='战斗描述')),
                ('combat_log', models.TextField(blank=True, verbose_name='战斗日志')),
                ('monster', models.TextField(blank=True, verbose_name='战斗日志')),
                ('character', models.TextField(blank=True, verbose_name='战斗日志')),
                ('card', models.TextField(blank=True, verbose_name='战斗日志')),
                ('loop', models.TextField(blank=True, verbose_name='战斗日志')),
                ('editor', models.CharField(blank=True, max_length=25, null=True, verbose_name='编辑人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('delete_flag', models.SmallIntegerField(default=0, verbose_name='删除标记')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '战斗',
            },
        ),
    ]
