# Generated by Django 3.2.4 on 2021-06-18 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simc', '0004_alter_battlefield_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battlefield',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='battlefield',
            name='editor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='编辑人'),
        ),
        migrations.AlterField(
            model_name='card',
            name='editor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='编辑人'),
        ),
        migrations.AlterField(
            model_name='character',
            name='editor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='编辑人'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='editor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='编辑人'),
        ),
    ]
