# Generated by Django 3.2.4 on 2021-06-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simc', '0004_auto_20210607_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='img',
            field=models.ImageField(null=True, upload_to='img/card/%Y/%m/%d/', verbose_name='封面'),
        ),
        migrations.AddField(
            model_name='card',
            name='material',
            field=models.CharField(default='undefined', max_length=25, verbose_name='施法材料'),
        ),
        migrations.AddField(
            model_name='card',
            name='power',
            field=models.IntegerField(default=1, verbose_name='费用'),
        ),
        migrations.AddField(
            model_name='card',
            name='waiver',
            field=models.TextField(default='undefined', verbose_name='豁免判定'),
        ),
        migrations.AddField(
            model_name='character',
            name='img',
            field=models.ImageField(null=True, upload_to='img/character/%Y/%m/%d/', verbose_name='封面'),
        ),
        migrations.AddField(
            model_name='monster',
            name='img',
            field=models.ImageField(null=True, upload_to='img/monster/%Y/%m/%d/', verbose_name='封面'),
        ),
    ]
