# Generated by Django 3.2.4 on 2021-06-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simc', '0005_auto_20210608_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlefield',
            name='editor',
            field=models.CharField(max_length=25, null=True, verbose_name='编辑人'),
        ),
        migrations.AddField(
            model_name='card',
            name='behavior_script',
            field=models.TextField(null=True, verbose_name='单位行为代码'),
        ),
        migrations.AddField(
            model_name='card',
            name='editor',
            field=models.CharField(max_length=25, null=True, verbose_name='编辑人'),
        ),
        migrations.AddField(
            model_name='character',
            name='behavior_script',
            field=models.TextField(null=True, verbose_name='单位行为代码'),
        ),
        migrations.AddField(
            model_name='character',
            name='editor',
            field=models.CharField(max_length=25, null=True, verbose_name='编辑人'),
        ),
        migrations.AddField(
            model_name='monster',
            name='behavior_script',
            field=models.TextField(null=True, verbose_name='单位行为代码'),
        ),
        migrations.AddField(
            model_name='monster',
            name='editor',
            field=models.CharField(max_length=25, null=True, verbose_name='编辑人'),
        ),
    ]
