# Generated by Django 3.2.4 on 2021-06-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simc', '0006_auto_20210608_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlefield',
            name='editor',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='编辑人'),
        ),
        migrations.AlterField(
            model_name='card',
            name='behavior_script',
            field=models.TextField(blank=True, null=True, verbose_name='单位行为代码'),
        ),
        migrations.AlterField(
            model_name='card',
            name='editor',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='编辑人'),
        ),
        migrations.AlterField(
            model_name='card',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/card/%Y/%m/%d/', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='character',
            name='behavior_script',
            field=models.TextField(blank=True, null=True, verbose_name='单位行为代码'),
        ),
        migrations.AlterField(
            model_name='character',
            name='editor',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='编辑人'),
        ),
        migrations.AlterField(
            model_name='character',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/character/%Y/%m/%d/', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='behavior_script',
            field=models.TextField(blank=True, null=True, verbose_name='单位行为代码'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='editor',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='编辑人'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/monster/%Y/%m/%d/', verbose_name='封面'),
        ),
    ]
