# Generated by Django 3.2.4 on 2021-06-16 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simc', '0007_auto_20210608_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battlefield',
            name='user_id',
        ),
    ]
