# Generated by Django 3.2.4 on 2021-06-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simc', '0008_remove_battlefield_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battlefield',
            name='id',
        ),
        migrations.AlterField(
            model_name='battlefield',
            name='combat_log',
            field=models.TextField(blank=True, verbose_name='战斗日志'),
        ),
        migrations.AlterField(
            model_name='battlefield',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='战斗名'),
        ),
        migrations.AlterField(
            model_name='battlefield',
            name='summary',
            field=models.TextField(blank=True, verbose_name='战斗描述'),
        ),
    ]
