# Generated by Django 3.2.4 on 2021-06-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simc', '0009_auto_20210616_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(choices=[('法术牌', 'Spells'), ('单位牌', 'Unit')], default='Spells', max_length=16, verbose_name='卡牌类型'),
        ),
    ]
